// getelementId

// function findElement() {
//     const element = document.getElementById("id1");
//     element.innerHTML = "element found!.......";
//     element.style.color="blu";
//     document.getElementById("id2").innerHTML = "hello world......!" 
// }


const node1 = document.getElementById("id2");
const node2 = document.getElementById("id3");
    function textNode1(){
        alert(node1.innerHTML);
    }
    function textNode2(){
        alert(node2.innerHTML);
    }